### ISSUE TITLE
DataSet

### ISSUE THREAD

**Issue by Arrcil** [lykaust15/SupportNet#4]
`#load Pfam dataset and encoding them into array
    functional_domain_encoding_list=Pfam.Pfam_from_pickle_file_encoding(
        '/home/liy0f/ec_project/data_and_feature/Pfam_name_list_new_data.pickle',
        '/home/liy0f/ec_project/data_and_feature/Pfam_model_names_list.pickle')`
Hello，about the two pickles,can you tell me how to get these and what datasets they  belong to in your paper, can you provide the two pickles for me ? thank you very much.

**Comment by liyu95** [comment]
Thank you very much for your interest in our project.
I am on a leave now and unable to deal with this issue right now.
I would try to solve your issue hopefully, on 13th. 
Thank you for your patience!

**Comment by liyu95** [comment]
Could you please give me your email?
Since this SupportNet paper has not been officially published, we cannot completely release the data. But we can send you the processed data (the pickle files) by email based on your request.

**Comment by Arrcil** [comment]
Thank you very much. My email is 17120432@bjtu.edu.cn

**Comment by liyu95** [comment]
Hi, I have send you the gdrive share link. Please let me know if if it does not work or you have more questions.

**Comment by Arrcil** [comment]
ok，there is a question.

Traceback (most recent call last):
  File "supportnet_ec.py", line 94, in <module>
    lambda: tf.constant(0.5, dtype=tf.float32))
  File "/home/xiaolin/.local/lib/python2.7/site-packages/tensorflow/python/util/                                                                               deprecation.py", line 432, in new_func
    return func(*args, **kwargs)
  File "/home/xiaolin/.local/lib/python2.7/site-packages/tensorflow/python/ops/c                                                                               ontrol_flow_ops.py", line 2040, in cond
    orig_res_t, res_t = context_t.BuildCondBranch(true_fn)
  File "/home/xiaolin/.local/lib/python2.7/site-packages/tensorflow/python/ops/c                                                                               ontrol_flow_ops.py", line 1890, in BuildCondBranch
    original_result = fn()
  File "supportnet_ec.py", line 93, in <lambda>
    tf.gather(final_feature, support_ind))/tf.cast(tf.size(support_ind),dtype=tf                                                                               .float32),
  File "/home/xiaolin/.local/lib/python2.7/site-packages/tensorflow/python/ops/m                                                                               ath_ops.py", line 874, in r_binary_op_wrapper
    x = ops.convert_to_tensor(x, dtype=y.dtype.base_dtype, name="x")
  File "/home/xiaolin/.local/lib/python2.7/site-packages/tensorflow/python/frame                                                                               work/ops.py", line 1011, in convert_to_tensor
    as_ref=False)
  File "/home/xiaolin/.local/lib/python2.7/site-packages/tensorflow/python/frame                                                                               work/ops.py", line 1107, in internal_convert_to_tensor
    ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)
  File "/home/xiaolin/.local/lib/python2.7/site-packages/tensorflow/python/frame                                                                               work/constant_op.py", line 217, in _constant_tensor_conversion_function
    return constant(v, dtype=dtype, name=name)
  File "/home/xiaolin/.local/lib/python2.7/site-packages/tensorflow/python/frame                                                                               work/constant_op.py", line 196, in constant
    value, dtype=dtype, shape=shape, verify_shape=verify_shape))
  File "/home/xiaolin/.local/lib/python2.7/site-packages/tensorflow/python/frame                                                                               work/tensor_util.py", line 424, in make_tensor_proto
    raise ValueError("None values not supported.")
ValueError: None values not supported.
Now, I am searching the solution about the problem.

**Comment by Arrcil** [comment]
ok，I don't know why the last issues is closed, there is a question.

Traceback (most recent call last):
File "supportnet_ec.py", line 94, in
lambda: tf.constant(0.5, dtype=tf.float32))
File "/home/xiaolin/.local/lib/python2.7/site-packages/tensorflow/python/util/ deprecation.py", line 432, in new_func
return func(*args, **kwargs)
File "/home/xiaolin/.local/lib/python2.7/site-packages/tensorflow/python/ops/c ontrol_flow_ops.py", line 2040, in cond
orig_res_t, res_t = context_t.BuildCondBranch(true_fn)
File "/home/xiaolin/.local/lib/python2.7/site-packages/tensorflow/python/ops/c ontrol_flow_ops.py", line 1890, in BuildCondBranch
original_result = fn()
File "supportnet_ec.py", line 93, in
tf.gather(final_feature, support_ind))/tf.cast(tf.size(support_ind),dtype=tf .float32),
File "/home/xiaolin/.local/lib/python2.7/site-packages/tensorflow/python/ops/m ath_ops.py", line 874, in r_binary_op_wrapper
x = ops.convert_to_tensor(x, dtype=y.dtype.base_dtype, name="x")
File "/home/xiaolin/.local/lib/python2.7/site-packages/tensorflow/python/frame work/ops.py", line 1011, in convert_to_tensor
as_ref=False)
File "/home/xiaolin/.local/lib/python2.7/site-packages/tensorflow/python/frame work/ops.py", line 1107, in internal_convert_to_tensor
ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)
File "/home/xiaolin/.local/lib/python2.7/site-packages/tensorflow/python/frame work/constant_op.py", line 217, in _constant_tensor_conversion_function
return constant(v, dtype=dtype, name=name)
File "/home/xiaolin/.local/lib/python2.7/site-packages/tensorflow/python/frame work/constant_op.py", line 196, in constant
value, dtype=dtype, shape=shape, verify_shape=verify_shape))
File "/home/xiaolin/.local/lib/python2.7/site-packages/tensorflow/python/frame work/tensor_util.py", line 424, in make_tensor_proto
raise ValueError("None values not supported.")
ValueError: None values not supported.
Now, I am searching the solution about the problem.

在2018-07-10 15:10:07，徐剑17120432@bjtu.edu.cn写道：

Thank you very much for your interest in our project.
I am on a leave now and unable to deal with this issue right now.
I would try to solve your issue hopefully, on 13th.
Thank you for your patience!
