### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by Arrcil** [lykaust15/SupportNet#5]
ok，I don't know why the last issues is closed, there is a question.

Traceback (most recent call last):
File "supportnet_ec.py", line 94, in 
lambda: tf.constant(0.5, dtype=tf.float32))
File "/home/xiaolin/.local/lib/python2.7/site-packages/tensorflow/python/util/ deprecation.py", line 432, in new_func
return func(*args, **kwargs)
File "/home/xiaolin/.local/lib/python2.7/site-packages/tensorflow/python/ops/c ontrol_flow_ops.py", line 2040, in cond
orig_res_t, res_t = context_t.BuildCondBranch(true_fn)
File "/home/xiaolin/.local/lib/python2.7/site-packages/tensorflow/python/ops/c ontrol_flow_ops.py", line 1890, in BuildCondBranch
original_result = fn()
File "supportnet_ec.py", line 93, in 
tf.gather(final_feature, support_ind))/tf.cast(tf.size(support_ind),dtype=tf .float32),
File "/home/xiaolin/.local/lib/python2.7/site-packages/tensorflow/python/ops/m ath_ops.py", line 874, in r_binary_op_wrapper
x = ops.convert_to_tensor(x, dtype=y.dtype.base_dtype, name="x")
File "/home/xiaolin/.local/lib/python2.7/site-packages/tensorflow/python/frame work/ops.py", line 1011, in convert_to_tensor
as_ref=False)
File "/home/xiaolin/.local/lib/python2.7/site-packages/tensorflow/python/frame work/ops.py", line 1107, in internal_convert_to_tensor
ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)
File "/home/xiaolin/.local/lib/python2.7/site-packages/tensorflow/python/frame work/constant_op.py", line 217, in _constant_tensor_conversion_function
return constant(v, dtype=dtype, name=name)
File "/home/xiaolin/.local/lib/python2.7/site-packages/tensorflow/python/frame work/constant_op.py", line 196, in constant
value, dtype=dtype, shape=shape, verify_shape=verify_shape))
File "/home/xiaolin/.local/lib/python2.7/site-packages/tensorflow/python/frame work/tensor_util.py", line 424, in make_tensor_proto
raise ValueError("None values not supported.")
ValueError: None values not supported.
Now, I am searching the solution about the problem.

**Comment by Arrcil** [comment]
Hello？ Can you see my question？？ I don't know how to deal with it.

**Comment by liyu95** [comment]
Sorry for the late reply. Did not notice that until just now.
What's you tensorflow version? I guess you are using a very new version of tensorflow, and some interface has been changedd. I am using 1.0
